version: "3"

services:
  influxdb:
    image: influxdb:1.8.4
    container_name: influxdb
    restart: unless-stopped
    env_file:
      - env.influxdb
    volumes:
      - influxdb-data:/var/lib/influxdb
    logging:
      options:
        max-size: "50m"

  grafana:
    image: grafana:6.7.4-with-plugins
    build:
      context: ./grafana-with-plugins
      dockerfile: Dockerfile
      args:
        GRAFANA_VERSION: 6.7.6
        GF_INSTALL_PLUGINS: grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource,flant-statusmap-panel
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - env.grafana
    links:
      - influxdb
    volumes:
      - grafana-data:/var/lib/grafana
    logging:
      options:
        max-size: "50m"

volumes:
  influxdb-data:
    external:
      name: influxdb-data

  grafana-data:
    external:
      name: grafana-data

networks:
  default:
    external:
       name: influxdb-net
