influxdb:
  image: influxdb:1.7.6
  container_name: influxdb
  ports:
    - "8086:8086"
  env_file:
    - env.influxdb
  volumes:
    - influxdb-data:/var/lib/influxdb

grafana:
  image: grafana/grafana:6.1.6
  container_name: grafana
  ports:
    - "3000:3000"
  env_file:
    - env.grafana
  links:
    - influxdb
  volumes:
    - grafana-data:/var/lib/grafana
