version: "3"

services:
  influxdb:
    image: influxdb:1.7.6
    container_name: influxdb
    restart: always
    env_file:
      - env.influxdb
    volumes:
      - influxdb-data:/var/lib/influxdb

  grafana:
    image: grafana:6.1.6-with-plugins
    build:
      context: ./grafana-with-plugins
      dockerfile: Dockerfile
      args:
        GRAFANA_VERSION: 6.1.6
        GF_INSTALL_PLUGINS: grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource,flant-statusmap-panel
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - env.grafana
    links:
      - influxdb
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  influxdb-data:
    external:
      name: influxdb-data

  grafana-data:
    external:
      name: grafana-data

networks:
  default:
    external:
       name: influx-net
